import Config

if config_env() == :prod do
  secret_key_base =
    System.get_env("SECRET_KEY_BASE") ||
      raise """
      environment variable SECRET_KEY_BASE is missing.
      You can generate one by calling: mix phx.gen.secret
      """

  # OPERATOR_PASSWORD can be set via env or generated by entrypoint
  operator_password = System.get_env("OPERATOR_PASSWORD")

  host = System.get_env("PHX_HOST") || "localhost"
  port = String.to_integer(System.get_env("PORT") || "4000")

  if operator_password do
    config :custyard, :operator_password, operator_password
  end

  config :custyard, CustyardWeb.Endpoint,
    url: [host: host, port: 443, scheme: "https"],
    http: [
      ip: {0, 0, 0, 0, 0, 0, 0, 0},
      port: port
    ],
    secret_key_base: secret_key_base

  config :custyard, Custyard.Repo,
    database: System.get_env("DATABASE_PATH") || "/data/custyard.db",
    pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10")
end
