import Config

# Configure Swoosh mailer for production
if config_env() == :prod do
  # Mail configuration (optional - falls back to Local adapter if not set)
  mail_adapter = System.get_env("MAIL_ADAPTER")

  if mail_adapter do
    case mail_adapter do
      "mailgun" ->
        config :custyard, Custyard.Mailer,
          adapter: Swoosh.Adapters.Mailgun,
          api_key: System.get_env("MAILGUN_API_KEY"),
          domain: System.get_env("MAILGUN_DOMAIN")

      "sendgrid" ->
        config :custyard, Custyard.Mailer,
          adapter: Swoosh.Adapters.Sendgrid,
          api_key: System.get_env("SENDGRID_API_KEY")

      "smtp" ->
        config :custyard, Custyard.Mailer,
          adapter: Swoosh.Adapters.SMTP,
          relay: System.get_env("SMTP_HOST"),
          port: String.to_integer(System.get_env("SMTP_PORT") || "587"),
          username: System.get_env("SMTP_USERNAME"),
          password: System.get_env("SMTP_PASSWORD"),
          ssl: System.get_env("SMTP_SSL") == "true",
          tls: :always,
          auth: :always

      _ ->
        # Unknown adapter, keep Local
        :ok
    end
  end
end

if config_env() == :prod do
  secret_key_base =
    System.get_env("SECRET_KEY_BASE") ||
      raise """
      environment variable SECRET_KEY_BASE is missing.
      You can generate one by calling: mix phx.gen.secret
      """

  # OPERATOR_PASSWORD can be set via env or generated by entrypoint
  operator_password = System.get_env("OPERATOR_PASSWORD")

  host = System.get_env("PHX_HOST") || "localhost"
  port = String.to_integer(System.get_env("PORT") || "4000")

  if operator_password do
    config :custyard, :operator_password, operator_password
  end

  config :custyard, CustyardWeb.Endpoint,
    url: [host: host, port: 443, scheme: "https"],
    http: [
      ip: {0, 0, 0, 0, 0, 0, 0, 0},
      port: port
    ],
    secret_key_base: secret_key_base

  config :custyard, Custyard.Repo,
    database: System.get_env("DATABASE_PATH") || "/data/custyard.db",
    pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10")
end
